name: CI

on: [push, pull_request]

jobs:
  # This workflow contains a single job called "test"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - run: npm ci
      - run: npm test

